<a href="https://colab.research.google.com/github/rs-saran/Pytorch-practice/blob/main/Pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [12]:
#tensors are similar to numpy nd arrays

x = torch.tensor([1,2,3,4])
y = torch.tensor([[1],[2]])
z = torch.tensor([[1,2]])

In [13]:
x.shape

torch.Size([4])

In [14]:
x1 = x.view(2,2)
x1.shape

torch.Size([2, 2])

In [4]:
y.shape

torch.Size([2, 1])

In [7]:
z.shape

torch.Size([1, 2])

In [8]:
torch.tensor([[[1],[2]]]).shape

torch.Size([1, 2, 1])

In [9]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [15]:
# similar to numpy zeros, ones, randint, randn
# .add -> element wise addition
# * -> element wise multiplication

In [16]:
w = torch.randint(low = 1, high = 10, size = (2,3))
w

tensor([[7, 9, 3],
        [3, 8, 9]])

In [17]:
w.add(1)

tensor([[ 8, 10,  4],
        [ 4,  9, 10]])

In [18]:
w*2

tensor([[14, 18,  6],
        [ 6, 16, 18]])

In [19]:
w.multiply(3)

tensor([[21, 27,  9],
        [ 9, 24, 27]])

In [ ]:
# reshaping
#.view --> like numpy reshpae
# .squeeze -->